/*INSERT INTO DEPARTAMENTO (ID, NOME) VALUES (1, 'Compras');
INSERT INTO DEPARTAMENTO (ID, NOME) VALUES (2, 'T.I');
INSERT INTO DEPARTAMENTO (ID, NOME) VALUES (3, 'Marketing');
INSERT INTO DEPARTAMENTO (ID, NOME) VALUES (4, 'Suporte');*/